export { default as Home } from './home'
export { default as WebCompanies } from './companies'
export { default as WebTemplates } from './templates'
export { default as About } from './about'
export { default as Job } from './jobs'